### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by davidnevadoc**
Solve the current CI check fails

### CODE REVIEW

**Comment by davidnevadoc** [comment]
The error in `intra-doc-links` is due to  [this issue](https://github.com/rust-lang/rust/issues/93476). Probably will be fixed in the next copule days.

**Comment by davidnevadoc** [comment]
We should consider fixing a version `rust-toolchain` and update it manually in order to avoid these issues.

**Review by CPerezz — APPROVED** [review]
LGTM!!!!!!

**Review by LukePearson1 — APPROVED** [review]
Thanks for finding the issue. @davidnevadoc

**Review by mathcrypto — APPROVED** [review]

**Pull request merged**
