### PR TITLE
Add test for permutation argument constants.

### LINKED ISSUE #154: Testing coset constants
The constants we are currently using for generating `H` cosets for the permutation argument are correct for the fields currently used (`Bls` scalar fields). However we should have a test that ensures these constants are valid. Specially considering the addition of more wires (and therefore more constants) and other supported fields.

### PR DESCRIPTION
**Pull request by davidnevadoc**
Close #154

### CODE REVIEW

**Review by CPerezz — APPROVED** [review]
How much time doesnthis take to run?? Wondering if we should ignore or not.

Aside from that, great work mate!

**Comment by akinovak** [comment]
Wow looks so great and clean! Should we also put a hackmd link on top of the file?

@CPerezz for not I guess it might be ignored, but I think we need to include it as soon as we switch to arbitrary number of wires.

**Comment by davidnevadoc** [comment]
This runs pretty quick. Takes `O(k^2)` multiplications with `k` being the number of wires which its usually not too large.
I think right now having the constants hardcoded this is fine to have as a test. If at some point we generate them in some other way this may be part of the generation algorithm.

**Comment by weikengchen** [comment]
Why is `prev_cts` never updated?

**Comment by davidnevadoc** [comment]
> Why is `prev_cts` never updated?

I forgot to update it at the end of the loop. Well spotted! :+1:

**Review by weikengchen — APPROVED** [review]

**Comment by weikengchen** [comment]
I feel it is ready to merge.

**Pull request merged**
